export {default as Search} from './Search'
export {default as Compare} from './Compare'
export {default as Recommend} from './Recommend'
export {default as Record} from './Record'
export {default as Comment} from './Comment'